// Mocks generated by Mockito 5.4.6 from annotations
// in myraid_tasks/test/providers/task_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myraid_tasks/data/models/task_model.dart' as _i2;
import 'package:myraid_tasks/data/repositories/task_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaskModel_0 extends _i1.SmartFake implements _i2.TaskModel {
  _FakeTaskModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i3.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.TaskModel>> getTasks({
    required int? userId,
    int? skip = 0,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, [], {
              #userId: userId,
              #skip: skip,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<_i2.TaskModel> createTask({
    required String? title,
    required String? description,
    required _i2.TaskStatus? status,
    DateTime? dueDate,
    required int? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [], {
              #title: title,
              #description: description,
              #status: status,
              #dueDate: dueDate,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(
                this,
                Invocation.method(#createTask, [], {
                  #title: title,
                  #description: description,
                  #status: status,
                  #dueDate: dueDate,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.TaskModel>);

  @override
  _i4.Future<_i2.TaskModel> updateTask(_i2.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i4.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(this, Invocation.method(#updateTask, [task])),
            ),
          )
          as _i4.Future<_i2.TaskModel>);

  @override
  _i4.Future<void> deleteTask(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
